http://localhost:5508/zara/item?url=https://www.zara.com/share/straight-blazer-zw-collection-p08771510.html?v1=402153953&v2=2420942&utm_campaign=productShare&utm_medium=mobile_sharing_iOS&utm_source=red_social_movil

###
http://localhost:5508/follow/123
###
POST http://localhost:5508/follow/123?url=https://www.zara.com/share/straight-blazer-zw-collection-p08771510.html?v1=402153953&v2=2420942&utm_campaign=productShare&utm_medium=mobile_sharing_iOS&utm_source=red_social_movil

###
http://localhost:5508/zara/item?url=https://www.zara.com/share/straight-blazer-zw-collection-p08771510.html?v1=402153953&v2=2420942&utm_campaign=productShare&utm_medium=mobile_sharing_iOS&utm_source=red_social_movil

###
http://localhost:5508/follow/123
###
POST http://localhost:5508/follow/123?url=http://localhost:5508/zara/item?url=https://www.zara.com/share/straight-blazer-zw-collection-p08771510.html?v1=402153953&v2=2420942&utm_campaign=productShare&utm_medium=mobile_sharing_iOS&utm_source=red_social_movil