
GET dock
accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
accept-language: en-US,en;q=0.9
priority: u=0, i
sec-ch-ua: "Chromium";v="142", "Google Chrome";v="142", "Not_A Brand";v="99"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "macOS"
sec-fetch-dest: document
sec-fetch-mode: navigate
sec-fetch-site: none
sec-fetch-user: ?1
upgrade-insecure-requests: 1

> {%
  const cookies = response.headers.valuesOf("set-cookie") ?? [];
  const akCookie = cookies
    .map(cookie => cookie.split(";")[0])
    .find(cookie => cookie.startsWith("ak_bmsc="));

  if (akCookie) {
    client.global.set("ak_cookie", akCookie);
  }
%}

###

GET https://www.zara.com/interstitial/ic.html
accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
accept-language: en-US,en;q=0.9
priority: u=0, i
sec-ch-ua: "Chromium";v="142", "Google Chrome";v="142", "Not_A Brand";v="99"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "macOS"
sec-fetch-dest: iframe
sec-fetch-mode: navigate
sec-fetch-site: same-origin
upgrade-insecure-requests: 1
cookie: {{ak_cookie}}
referer: https://www.zara.com/nl/en/heavyweight-regular-fit-basic-t-shirt-p01887455.html?v1=452744597

###
https://www.zara.com/itxrest/1/catalog/store/11709/product/id/452744597/availability

###
https://www.zara.com/itxrest/1/catalog/store/11709/product/id/452744597
